# This file was generated by GoReleaser. DO NOT EDIT.
cask "leancommit" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "979fd2ddf241a6a2d233056b0dbf47e355a7193cea3c500d9706762c2933bd4b"
      url "https://github.com/tombenner/leancommit/releases/download/v#{version}/leancommit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28f1df85dd65942fd2a49b83fa3f6f3466477b88b52a591db828517c9d984c75"
      url "https://github.com/tombenner/leancommit/releases/download/v#{version}/leancommit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1d158fca70bc06c6b3f5a179f75552962dabd57240efaf7a94405b903dd84be"
      url "https://github.com/tombenner/leancommit/releases/download/v#{version}/leancommit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5bc122c17248695489b53432ac726c5fc8e5e54e79eec304174d77150b76ed06"
      url "https://github.com/tombenner/leancommit/releases/download/v#{version}/leancommit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "leancommit"
  desc "Auto-generate commit messages from the latest Codex plan titles."
  homepage "https://github.com/tombenner/leancommit"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "leancommit"

  # No zap stanza required

  caveats <<~EOS
    LeanCommit is not signed or notarized. If macOS blocks the binary,
    remove the quarantine attribute manually:

      xattr -dr com.apple.quarantine "$(brew --prefix)/bin/leancommit"
  EOS
end
