# This file was generated by GoReleaser. DO NOT EDIT.
cask "leancommit" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "8585dd1117a7ba8a8261e20fa06abc24ef04b26395bf7204f864d0dcb71f85dd"
      url "https://github.com/tombenner/leancommit/releases/download/v#{version}/leancommit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "61e8d9f15c2223280a26ad0e9683d2bf701c8f42eec62d2f4451411849c55099"
      url "https://github.com/tombenner/leancommit/releases/download/v#{version}/leancommit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f01523d19ecda591b5f2c23932ddf3f9999903793a699a289bf05843fa73dd3e"
      url "https://github.com/tombenner/leancommit/releases/download/v#{version}/leancommit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f95612c8aef10b5aa566d94e7fb4fb5775b9be1f3f25b997be1d30b3208c98ed"
      url "https://github.com/tombenner/leancommit/releases/download/v#{version}/leancommit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "leancommit"
  desc "Auto-generate commit messages from the latest Codex plan titles."
  homepage "https://github.com/tombenner/leancommit"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "leancommit"

  # No zap stanza required

  caveats <<~EOS
    LeanCommit is not signed or notarized. If macOS blocks the binary,
    remove the quarantine attribute manually:

      xattr -dr com.apple.quarantine "$(brew --prefix)/bin/leancommit"
  EOS
end
