# This file was generated by GoReleaser. DO NOT EDIT.
cask "leancommit" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "15476fc4ed2b050e1bf8f7d250a2a425c179962d4c35bbc07e9a0b500baf6fd0"
      url "https://github.com/tombenner/leancommit/releases/download/v#{version}/leancommit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd55fe0906e0a3f2d03bb48ec77171c411d4780c41e64d6fd6efc98672d28537"
      url "https://github.com/tombenner/leancommit/releases/download/v#{version}/leancommit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "58493c64e090fa58badf43c7bc1fb7a1c527dfeca3b255ec47025ae54859584f"
      url "https://github.com/tombenner/leancommit/releases/download/v#{version}/leancommit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d933df8480057f0bdd808bfd483d7ccdfc8fdefc323c9c8671275b1ba370d3e0"
      url "https://github.com/tombenner/leancommit/releases/download/v#{version}/leancommit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "leancommit"
  desc "Auto-generate commit messages from the latest Codex plan titles."
  homepage "https://github.com/tombenner/leancommit"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "leancommit"

  # No zap stanza required

  caveats <<~EOS
    LeanCommit is not signed or notarized. If macOS blocks the binary,
    remove the quarantine attribute manually:

      xattr -dr com.apple.quarantine "$(brew --prefix)/bin/leancommit"
  EOS
end
